### ISSUE TITLE
"Cannot read the array lenght" error

### ISSUE THREAD

**Issue by TonyMontero** [mrxbox98/AdvancedFlags#1]
Hello there! I love your plugin I must say but i'm experiencing this issue when trying to use the main command

`[23:14:25 INFO]: PacoCalvicie issued server command: /advancedflags:af
[23:14:25 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'advancedflags:af' in plugin AdvancedFlags v1.0.8 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.1.jar:git-Purpur-1316]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1316]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2309) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2120) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2101) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1316]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1316]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

When the plugin loads in the console this shows up:

`[23:12:18] [Server thread/ERROR]: Error occurred while enabling AdvancedFlags v1.0.8 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
	at me.mrxbox98.advancedflags.flags.CustomFlags.setupCustomFlags(CustomFlags.java:18) ~[AdvancedFlags-1.0.8.jar:?]
	at me.mrxbox98.advancedflags.AdvancedFlags.onEnable(AdvancedFlags.java:51) ~[AdvancedFlags-1.0.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1316]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1316]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1316]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Purpur-1316]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Purpur-1316]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1316]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1316]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1316]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1316]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:12:18] [Server thread/INFO]: [AdvancedFlags] Disabling AdvancedFlags v1.0.8`

Im using Purpur, a direct Paper fork (build 1316)
server version 1.17.1
plugin version: 1.0.8

**Comment by mrxbox98** [comment]
Thanks for the bug report. I just released a new update that should fix the problem. If you are still having this error reopen the issue.
