### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Jorc0** [mrxbox98/AdvancedFlags#2]
```
[AdvancedFlags] Plugin AdvancedFlags v1.1.7 generated an exception while executing
task 21
java.lang.NullPointerException: Cannot read field "rotate" because the return value of "me.mrxbox98.
advancedflags.utils.AdvancedPlayer.getAdvancedPlayer(org.bukkit.entity.Player)" is null
        at me.mrxbox98.advancedflags.AdvancedFlags$2.run(AdvancedFlags.java:126) ~[AdvancedFlags-1.1
.7.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.1
7.1.jar:git-Purpur-1331]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pa
tched_1.17.1.jar:git-Purpur-1331]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapp
er.java:22) ~[patched_1.17.1.jar:git-Purpur-1331]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by mrxbox98** [comment]
Fixed in latest version.
