### ISSUE TITLE
[Bug]: Error when starting up plugin

### ISSUE THREAD

**Issue by Jabilee** [mrxbox98/AdvancedFlags#7]
### What happened?

` Error occurred while enabling AdvancedFlags v1.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/ParticleParam
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3137) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3342) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2151) ~[?:?]
        at me.mrxbox98.particleapi.core.ParticleNativeCore.setupCore(ParticleNativeCore.java:69) ~[?:?]
        at me.mrxbox98.particleapi.core.ParticleNativeCore.loadAPI(ParticleNativeCore.java:46) ~[?:?]
        at me.mrxbox98.advancedflags.AdvancedFlags.onEnable(AdvancedFlags.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at com.mohistmc.util.pluginmanager.PluginManagers.reloadPluginCommand(PluginManagers.java:132) ~[forge:?]
        at com.mohistmc.command.PluginCommand.execute(PluginCommand.java:69) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:171) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:775) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1829) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1664) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:938) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:175) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:921) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:915) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:901) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]`

### Version

1.16

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jabilee** [comment]
Changed my server to arclight from mohist.
